![imagen](./img/ejercicios.png)

In [1]:
import numpy as np

## Ejercicio 1
1. Crea un array que vaya del 0 al 9 y que se llame `my_array`
2. Imprime por pantalla los elementos [9 7 5 3 1] en ese orden, usando numpy.

In [22]:
my_array = np.arange(10)
print(np.flip(my_array[my_array %2 == 1]))

[9 7 5 3 1]


## Ejercicio 2
Imprime por pantalla la secuencia [8 7] del array `my_array`

In [3]:
print(my_array[8: 6: -1])

[8 7]


## Ejercicio 3
Imprime por pantalla la secuencia [2 1 0] de `my_array`

In [4]:
print(my_array[2::-1])

[2 1 0]


## Ejercicio 4
1. Crea una matriz de 4x5, con una secuencia del 1 al 20
2. Invierte totalmente la matriz. Tanto las filas, como las columnas

In [5]:
matriz = np.arange(1, 21).reshape(5, 4)
print(matriz)

# invertida = np.flip(matriz.copy())
invertida = matriz[::-1, ::-1]
print(invertida)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]]
[[20 19 18 17]
 [16 15 14 13]
 [12 11 10  9]
 [ 8  7  6  5]
 [ 4  3  2  1]]



## Ejercicio 5

Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[1, 2],
       [6, 7]])
```

In [23]:
print(np.array([[matriz[0,0], matriz[0,1]], [matriz[1, 1], matriz[1, 2]]]))
print(matriz[:2, :2])

[[1 2]
 [6 7]]
[[1 2]
 [5 6]]


## Ejercicio 6
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[ 1,  3,  5],
       [11, 13, 15]])
```

In [27]:
print(matriz)
print("")
print(np.array([[matriz[0,0], matriz[0,2], matriz[1, 0]], [matriz[2,2], matriz[3,0], matriz[3,2]]]))

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]]

[[ 1  3  5]
 [11 13 15]]


In [8]:
print(matriz)
print("")
vector_m = matriz.flatten()
indices = [0, 2, 4]
indices_plus = [ i + 10 for i in indices]
resultado = vector_m[indices + indices_plus].reshape(2, 3)
print(resultado)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]]

[[ 1  3  5]
 [11 13 15]]


## Ejercicio 7
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[ 5,  4,  3,  2,  1],
       [10,  9,  8,  7,  6],
       [15, 14, 13, 12, 11]])
```

In [31]:
print(matriz)
print("")
np.fliplr(vector_m[0: 15].reshape(3, 5))
# np.flipud(vector_m[0: 15].reshape(3, 5))

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]]



array([[ 5,  4,  3,  2,  1],
       [10,  9,  8,  7,  6],
       [15, 14, 13, 12, 11]])

## Ejercicio 8
Dado el siguiente array:

```Python
x = np.array(["Loro", "Perro", "Gato", "Loro", "Perro"])
```

Filtra el array para quedarte únicamente con los loros.

Resuélvelo de dos maneras diferentes

In [34]:
x = np.array(["Loro", "Perro", "Gato", "Loro", "Perro"])
mascara = np.array(x == "Loro")
loros = x[mascara]
print(loros)


['Loro' 'Loro']


In [36]:
indices = np.where(x == "Loro")
print(x[indices])

['Loro' 'Loro']


## Ejercicio 9
Crea una secuencia de 20 elementos y transfórmala en un array compuesto por 2 matrices de 5x2

In [115]:
secuencia = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]
np.array(secuencia).reshape(2, 5, 2)

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6],
        [ 7,  8],
        [ 9, 10]],

       [[11, 12],
        [13, 14],
        [15, 16],
        [17, 18],
        [19, 20]]])

## Ejercicio 10

Crea un array de 10 0s. ¿Cuánto ocupa en memoria?

Sustituye el 4to elemento por 1, e imprime el array por pantalla

In [38]:
ceros =np.zeros(10, dtype=int)
ceros.nbytes
ceros[3]= 1
print(ceros)

[0 0 0 1 0 0 0 0 0 0]


## Ejercicio 11

Crea un vector que vaya del 10 al 49

Inviértelo

In [123]:
print(np.arange(10, 50)[::-1])

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


## Ejercicio 12
Encuentra los índices de los valores que no sean 0 del siguiente vector [1,2,0,0,4,0]. El output sería [1, 2 4]. [Encuentra el método apropiado en la documentación.](https://numpy.org/doc/) Encapsúlalo en una función, con un argumento de entrada de un vector.

In [131]:
victor = np.array([1, 2, 0, 0, 4, 0])

def encuentra_cero(vector):
    mascara = np.array(vector != 0)
    return vector[mascara]
    # return np.nonzero(vector)[0]

encuentra_cero(victor)

#El output propuesto está mal, son los valores, no los índices

array([1, 2, 4])

In [ ]:
def encuentra_no_cero(vector):
    # nonzero() devuelve una tupla de arrays, tomamos el primer elemento [0]
    # que contiene los índices de los elementos no nulos
    return np.nonzero(vector)[0]

encuentra_no_cero(victor)

## Ejercicio 13
Crea una matriz de números aleatorios 10x10. Encuentra los valores mínimo y máximo.

In [10]:
decana = np.random.randint(100, size=(10, 10))
print(decana)

print(np.min(decana))
print(np.max(decana))

[[24 76 33 90 27 10 74 90 33 73]
 [42  7  6 10 48 17 99 21 61 80]
 [61 64 75 29  8 29 31 16 49 83]
 [81 52 34 75 50 50 68 76 29 75]
 [37 40 81 51 21 26 39  4 61 11]
 [80 58 17 38  6 63 69 80 84 97]
 [67 14 97 49 29 63 18 52 40 55]
 [55 71 17 27 14 24  6 27 10 49]
 [78 31 10 73  6 54  0 76 44 44]
 [61 48 32 71 92 72 63 42 53 41]]
0
99


## Ejercicio 14
Crea un vector aleatorio de tamaño 30 y calcula su media

In [9]:
alfa = np.random.randint(30, size=30)
print(alfa)

print(np.mean(alfa))

[26  7 24  2 22 17  2  7  8 19 18 16  8 16 10 16  5 19 23 20  1 18  1  7
 13  3 22  8 17 24]
13.3


## Ejercicio 15
Crea un array cuadrado de 2D, con las dimensiones que quieras, pero que todo el borde esté compuesto por 1s, y el interior por 0s

In [95]:
cuadrado = np.ones(16).reshape(4, 4)
cuadrado[1:-1, 1:-1] = 0
print(cuadrado)

[[1. 1. 1. 1.]
 [1. 0. 0. 1.]
 [1. 0. 0. 1.]
 [1. 1. 1. 1.]]


In [100]:
# Mala forma, 2 variables ocupan el doble de memoria
matriz_4x4 = np.zeros((4, 4), dtype=int)
matriz_5x5 = np.pad(matriz_4x4, pad_width=1, mode='constant', constant_values=1)
print(matriz_5x5)

[[1 1 1 1 1 1]
 [1 0 0 0 0 1]
 [1 0 0 0 0 1]
 [1 0 0 0 0 1]
 [1 0 0 0 0 1]
 [1 1 1 1 1 1]]


## Ejercicio 16
Crea una matriz de 8x8, y rellénala con 0s y 1s. Tienes que replicar:
```Python
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
```

In [102]:
octava = np.zeros(64).reshape(8, 8)
indices = octava.flatten()
indices[1::2] = 1
indices[8::8*2] = 20

# NO me funcionó
# print(indices.reshape(8, 8))

In [104]:
octava = np.zeros((8, 8), dtype=int)
octava[0::2, 1::2] = 1
octava[1::2, 0::2] = 1

print(octava)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


## Ejercicio 17
Replica la matriz del apartado anterior, pero en este caso usando [la función `tile`](https://numpy.org/doc/stable/reference/generated/numpy.tile.html)

In [107]:
print(np.tile([[0, 1],[1, 0]], (8, 8)))

[[0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0]]


## Ejercicio 18
Crea una matriz aleatoria de 5x5 y normaliza sus valores. Para normalizar tienes que restar sus valores por la media(`np.mean`) y dividir el resultado por la desviación estándar(`np.std`).

In [17]:
quintal = np.random.randint(25, size=100)
print(quintal)
media = np.mean(quintal)
desviacion = np.std(quintal)
normalizado = (quintal - media) / desviacion
print(normalizado)


[23 15  2 14  0 23  7 16 11 19 10 14  7 23  1  4 11 11  2 20 10 18 10 19
 16 12 16 16  5 11 13 23  4 12 21 10  8 14 22  5  9 14  0 17 19 15 22 24
 14 14 21 20 14  3 24 16  0 10 17 10 15 15  1  7  6  4 17 18  8  9 12 22
 24  4 20 13  2  2 16 24 10 24 18 24  5  5 20  7  5  4 17 15  9  6 19 15
 11  7  1 13]
[ 1.51612567  0.3554553  -1.53063405  0.2103715  -1.82080165  1.51612567
 -0.80521507  0.5005391  -0.22487988  0.93579049 -0.36996368  0.2103715
 -0.80521507  1.51612567 -1.67571785 -1.24046646 -0.22487988 -0.22487988
 -1.53063405  1.08087428 -0.36996368  0.79070669 -0.36996368  0.93579049
  0.5005391  -0.07979609  0.5005391   0.5005391  -1.09538266 -0.22487988
  0.06528771  1.51612567 -1.24046646 -0.07979609  1.22595808 -0.36996368
 -0.66013127  0.2103715   1.37104188 -1.09538266 -0.51504748  0.2103715
 -1.82080165  0.64562289  0.93579049  0.3554553   1.37104188  1.66120947
  0.2103715   0.2103715   1.22595808  1.08087428  0.2103715  -1.38555026
  1.66120947  0.5005391  -1.82080165 -0

## Ejercicio 19
1. Crea una secuencia de números que vayan del 0 al 10.
2. Crea un nuevo array, que parta del anterior, pero sustituya por el valor -1, todos los elementos cuyo valor se encuentre entre el 3 y el 8.
3. Crea un nuevo array que niegue todos los elementos entre el 3 y el 8

In [108]:
omega = np.arange(11)
mascara = (omega >= 3) & (omega <=8)
omega_dos = omega.copy()
omega_dos[mascara] = -1
print(omega_dos)
gamma = omega.copy()
gamma[mascara] = -gamma[mascara]
print(gamma)

[ 0  1  2 -1 -1 -1 -1 -1 -1  9 10]
[ 0  1  2 -3 -4 -5 -6 -7 -8  9 10]


In [111]:
seq = np.arange(11)
epsilon = np.where((seq > 3) & (seq < 8), -1, seq)

delta = np.where((seq > 3) & (seq < 8), -seq, seq)
print(epsilon)
print(delta)

[ 0  1  2  3 -1 -1 -1 -1  8  9 10]
[ 0  1  2  3 -4 -5 -6 -7  8  9 10]
