![imagen](./img/ejercicios.png)

## Ejercicio 1
Importa el módulo de `numpy` y obtén su versión.

In [2]:
import numpy as np
print(np.__version__)

2.4.2


## Ejercicio 2
Crea un array de una dimensión que vaya de 0 a 9. Llamalo `my_array`

In [3]:
my_array = np.arange(10)
print(my_array)

[0 1 2 3 4 5 6 7 8 9]


## Ejercicio 3
Crea un array 3x3, que sea todo a True

In [4]:
triplete = np.array(my_array[0:-1:] >= 0)
print(triplete.reshape(3, 3))


[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [5]:
array = np.full((3, 3), True)
print(array)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [7]:
array = np.ones((3, 3), dtype = bool)
print(array)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


## Ejercicio 4
Extrae todos los impares de `my_array`

In [8]:
my_array = np.arange(10)
impares = np.array(my_array[1:10:2])
print(impares)

[1 3 5 7 9]


In [9]:
my_array = np.arange(10)
masc_imp = np.array(my_array %2 == 1)
impares = np.array(my_array[masc_imp])
print(masc_imp)
print(impares)

[False  True False  True False  True False  True False  True]
[1 3 5 7 9]


In [11]:
print(my_array[my_array %2 != 0])

[1 3 5 7 9]


## Ejercicio 5
En un nuevo array, sustituye todos los impares de `my_array` por -1

In [13]:
two_array = np.where(masc_imp, -1, my_array)
print(two_array)
print(my_array)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]
[0 1 2 3 4 5 6 7 8 9]


In [14]:
new_array_5 = my_array.copy()
new_array_5[new_array_5 % 2 != 0] = -1
print(new_array_5)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


## Ejercicio 6
En un nuevo array, sustituye todos los impares de `my_array` por -1. Esta vez usa `where`

In [ ]:
two_array = np.where(masc_imp, -1, my_array)
print(two_array)
print(my_array)
#ups

## Ejercicio 7
Convierte `my_array` en un nuevo array de dos dimensiones mediante `reshape`.

In [16]:
my_array = my_array.reshape(2, 5)
print(my_array)

[[0 1 2 3 4]
 [5 6 7 8 9]]


## Ejercicio 8
Concatena los siguientes arrays verticalmente

```Python
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
```

In [17]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)

c = np.vstack((a, b))
# print(a)
# print(b)
print(c)

[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [19]:
array_8 = np.concatenate((a, b))
print(array_8)

[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]


## Ejercicio 9
Concatena los siguientes arrays horizontamente

```Python
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
```

In [21]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)

c = np.hstack((a, b))
print(c)

[[0 1 2 3 4 1 1 1 1 1]
 [5 6 7 8 9 1 1 1 1 1]]


In [22]:
array_8 = np.concatenate((a, b), axis= 1)
print(array_8)

[[0 1 2 3 4 1 1 1 1 1]
 [5 6 7 8 9 1 1 1 1 1]]


## Ejercicio 10
Encuentra todos los elementos en común entre ambos arrays. [Para ello usa la función `intersect1d`](https://numpy.org/doc/stable/reference/generated/numpy.intersect1d.html)

```Python
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
```

In [23]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

c = np.intersect1d(a, b)
print(c)

[2 4]


## Ejercicio 11
Obtén la documentación acerca de la función `concatenate`

In [25]:
print(np.concatenate.__doc__)

Join a sequence of arrays along an existing axis.

Parameters
----------
a1, a2, ... : sequence of array_like
    The arrays must have the same shape, except in the dimension
    corresponding to `axis` (the first, by default).
axis : int, optional
    The axis along which the arrays will be joined.  If axis is None,
    arrays are flattened before use.  Default is 0.
out : ndarray, optional
    If provided, the destination to place the result. The shape must be
    correct, matching that of what concatenate would have returned if no
    out argument were specified.
dtype : str or dtype
    If provided, the destination array will have this dtype. Cannot be
    provided together with `out`.

    .. versionadded:: 1.20.0

casting : {'no', 'equiv', 'safe', 'same_kind', 'unsafe'}, optional
    Controls what kind of data casting may occur. Defaults to 'same_kind'.
    For a description of the options, please see :term:`casting`.

    .. versionadded:: 1.20.0

Returns
-------
res : ndarray
 

## Ejercicio 12
Crea un array unidimensional que vaya del 0 al 9. Llámalo `my_array`. 
1. Multiplica cada uno de los elementos de `my_array` por 10, en un nuevo array
2. Accede al primer elemento de `my_array`
3. Accede al último elemento de `my_array`
4. Imprime por pantalla los numeros del 1 al 7 de `my_array`

In [26]:
my_array = np.arange(10)

decenas = my_array * 10
print(decenas)

print(my_array[0])
print(my_array[-1])
print(my_array[1:8])

[ 0 10 20 30 40 50 60 70 80 90]
0
9
[1 2 3 4 5 6 7]


## Ejercicio 13
Crea un array manualmente de tres filas por tres columnas. Llámalo `my_matrix`

In [ ]:
my_matrix = np.array([[1,2,3], 
                      [4,5,6],
                      [7,8,9]])
print(my_matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [33]:
import pprint

pprint.pprint(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])


## Ejercicio 14
Obtén la siguiente secuencia:

```Python
[ 1,  4,  7, 10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43, 46, 49]
```

In [35]:
trienio = np.arange(1, 50, 3)
print(trienio)

[ 1  4  7 10 13 16 19 22 25 28 31 34 37 40 43 46 49]


## Ejercicio 15
Obtén la siguiente secuencia

```Python
[4., 3.75, 3.5 , 3.25, 3.  , 2.75, 2.5 , 2.25, 2., 1.75, 1.5 ,1.25]
```

In [36]:
secun = np.arange(4, 1, -0.25)
print(secun)

[4.   3.75 3.5  3.25 3.   2.75 2.5  2.25 2.   1.75 1.5  1.25]


## Ejercicio 16
Lee la imagen "numpy.png" usando Pillow, y guárdala en un array.

In [54]:
from PIL import Image

numpy = np.array(Image.open('./img/numpy.png'))

print(numpy)
print(numpy.shape)

[[[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]
  ...
  [0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]
  ...
  [0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]
  ...
  [0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]

 ...

 [[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]
  ...
  [0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]
  ...
  [0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]
  ...
  [0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]]
(306, 765, 4)


## Ejercicio 17
Crea un array de 4x1. A continuación convierte el array a un 2x2

In [63]:
cuaternario = np.arange(4).reshape(4,1)
print(cuaternario)
print("")
print(cuaternario.reshape(2,2))

[[0]
 [1]
 [2]
 [3]]

[[0 1]
 [2 3]]


## Ejercicio 18
Crea una secuencia aleatoria. La secuencia se tiene que componer de 4 matrices de 5x3. Serían 3 dimensiones diferentes.

In [66]:
aleta = np.random.randint(0, 40, (4, 5, 3))
print(aleta)

[[[23 15 16]
  [ 3 38 24]
  [ 3 16 36]
  [23 30 21]
  [36  9  7]]

 [[20 18 34]
  [30 19  3]
  [22 17 36]
  [ 5 10 20]
  [12 17 35]]

 [[ 0 32 20]
  [38  0 27]
  [32  1 18]
  [19 21  3]
  [28  3 16]]

 [[29  0 27]
  [25 10  7]
  [22 29 24]
  [ 9 33  8]
  [38 32 16]]]


In [65]:
print(np.random.rand(4, 5, 3))

[[[0.30379571 0.39311857 0.84350235]
  [0.40671343 0.14981706 0.67160004]
  [0.88139996 0.50510297 0.38988251]
  [0.58303139 0.89995288 0.17362816]
  [0.73535051 0.98840389 0.30942941]]

 [[0.10693723 0.2482125  0.13573636]
  [0.83454221 0.2322943  0.78975559]
  [0.1358569  0.60283819 0.32759787]
  [0.75573444 0.01514128 0.96460735]
  [0.32154644 0.31767596 0.86029909]]

 [[0.98563074 0.47416211 0.18566763]
  [0.32465879 0.95081439 0.84347291]
  [0.56587401 0.78931109 0.28166084]
  [0.97517171 0.81823023 0.87869281]
  [0.5047282  0.95620996 0.86807254]]

 [[0.05065193 0.5027086  0.5156375 ]
  [0.68087791 0.01349441 0.42204684]
  [0.322525   0.96450942 0.8887801 ]
  [0.72667796 0.47861117 0.52001189]
  [0.49841827 0.65868158 0.39193196]]]


In [69]:
secuencia = np.random.rand(4 * 5 * 3).reshape(4, 5, 3)
print(secuencia)

[[[0.75962747 0.85553977 0.52173413]
  [0.49155111 0.7145809  0.43913519]
  [0.13070355 0.75907803 0.89047815]
  [0.64946601 0.40972586 0.7941551 ]
  [0.79595558 0.14718526 0.6927751 ]]

 [[0.27882888 0.97341356 0.65784417]
  [0.25650633 0.69111701 0.07867605]
  [0.31344729 0.62292702 0.75674073]
  [0.27726931 0.4815663  0.26827197]
  [0.03167721 0.70303207 0.37865958]]

 [[0.98656489 0.38906237 0.23878437]
  [0.04103363 0.8902899  0.75879084]
  [0.47241878 0.02504734 0.42842414]
  [0.40916066 0.76387962 0.08496777]
  [0.79674508 0.66715146 0.31229317]]

 [[0.69650016 0.89219797 0.18523963]
  [0.03945525 0.27382904 0.37971699]
  [0.01166247 0.74103782 0.20533468]
  [0.93203581 0.81079057 0.95558338]
  [0.92074044 0.74170449 0.39201078]]]


## Ejercicio 19
Crea una matriz de 10x1, toda ella compuesta por `False`. Después transformalo en un 2x5

In [70]:
# decano = np.arange(10)
# decano = np.array(decano < 0).reshape(2,5)

decano = np.zeros(10, dtype=bool).reshape(2,5)

print(decano)

[[False False False False False]
 [False False False False False]]


## Ejercicio 20
Dado el siguiente array

```Python
x = np.random.randint(10, 20, size = (5,2,6))
```

1. ¿Cuántos elementos tiene el array?
2. ¿Cuántas dimensiones?
3. ¿Cuánta es la longitud cada dimensión?

In [77]:

x = np.random.randint(10, 20, size = (5,2,6))

In [76]:
print(x.size)
print(x.ndim)
print(x.shape)

60
3
(5, 2, 6)
